### ISSUE TITLE
Where is the code and pull requests from team members?

### ISSUE THREAD

**Issue by vbitner87** [Levitsky-Ilya/Info-Project#20]
На занятии команда довольно успешно отчитывается о статусе проекта, но тут движухи нет.

Где текущий код проект?
Где комиты от членов команды в транк? Увидел только один файлик от Марии.

**Comment by MashenKa737** [comment]
смотрите у каждого на его ветке. Я только вчера дописала всё, чтобы можно было вместе собрать.
